/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as AnalyticsDowntimeRouteImport } from './routes/analytics.downtime'
import { Route as AnalyticsOeeRouteImport } from './routes/analytics.oee'
import { Route as AnalyticsReportsRouteImport } from './routes/analytics.reports'
import { Route as AnalyticsScheduleRouteImport } from './routes/analytics.schedule'
import { Route as ComplianceIndexRouteImport } from './routes/compliance.index'
import { Route as ComplianceAuditRouteImport } from './routes/compliance.audit'
import { Route as ComplianceEbmrRouteImport } from './routes/compliance.ebmr'
import { Route as ComplianceSopRouteImport } from './routes/compliance.sop'
import { Route as EhsEmissionsRouteImport } from './routes/ehs.emissions'
import { Route as EhsHazardsRouteImport } from './routes/ehs.hazards'
import { Route as EhsIncidentsRouteImport } from './routes/ehs.incidents'
import { Route as EhsPpeRouteImport } from './routes/ehs.ppe'
import { Route as EnergyIndexRouteImport } from './routes/energy.index'
import { Route as EnergyCarbonRouteImport } from './routes/energy.carbon'
import { Route as EnergyUtilitiesRouteImport } from './routes/energy.utilities'
import { Route as EnergyWasteRouteImport } from './routes/energy.waste'
import { Route as InventoryFinishedRouteImport } from './routes/inventory.finished'
import { Route as InventoryProcurementRouteImport } from './routes/inventory.procurement'
import { Route as InventoryRawRouteImport } from './routes/inventory.raw'
import { Route as InventoryVendorsRouteImport } from './routes/inventory.vendors'
import { Route as PredictiveAlertsRouteImport } from './routes/predictive.alerts'
import { Route as PredictiveHealthRouteImport } from './routes/predictive.health'
import { Route as PredictiveSimulationRouteImport } from './routes/predictive.simulation'
import { Route as PredictiveWorkOrdersRouteImport } from './routes/predictive.work-orders'
import { Route as QualityCapaRouteImport } from './routes/quality.capa'
import { Route as QualityCoaRouteImport } from './routes/quality.coa'
import { Route as QualityIpcRouteImport } from './routes/quality.ipc'
import { Route as QualityReleaseRouteImport } from './routes/quality.release'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsPlantRouteImport } from './routes/settings.plant'
import { Route as SettingsSensorsRouteImport } from './routes/settings.sensors'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsDowntimeRoute = AnalyticsDowntimeRouteImport.update({
  id: '/analytics/downtime',
  path: '/analytics/downtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsOeeRoute = AnalyticsOeeRouteImport.update({
  id: '/analytics/oee',
  path: '/analytics/oee',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsReportsRoute = AnalyticsReportsRouteImport.update({
  id: '/analytics/reports',
  path: '/analytics/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsScheduleRoute = AnalyticsScheduleRouteImport.update({
  id: '/analytics/schedule',
  path: '/analytics/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceAuditRoute = ComplianceAuditRouteImport.update({
  id: '/compliance/audit',
  path: '/compliance/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceEbmrRoute = ComplianceEbmrRouteImport.update({
  id: '/compliance/ebmr',
  path: '/compliance/ebmr',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceSopRoute = ComplianceSopRouteImport.update({
  id: '/compliance/sop',
  path: '/compliance/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const EhsEmissionsRoute = EhsEmissionsRouteImport.update({
  id: '/ehs/emissions',
  path: '/ehs/emissions',
  getParentRoute: () => rootRouteImport,
} as any)
const EhsHazardsRoute = EhsHazardsRouteImport.update({
  id: '/ehs/hazards',
  path: '/ehs/hazards',
  getParentRoute: () => rootRouteImport,
} as any)
const EhsIncidentsRoute = EhsIncidentsRouteImport.update({
  id: '/ehs/incidents',
  path: '/ehs/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const EhsPpeRoute = EhsPpeRouteImport.update({
  id: '/ehs/ppe',
  path: '/ehs/ppe',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyIndexRoute = EnergyIndexRouteImport.update({
  id: '/energy/',
  path: '/energy/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyCarbonRoute = EnergyCarbonRouteImport.update({
  id: '/energy/carbon',
  path: '/energy/carbon',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyUtilitiesRoute = EnergyUtilitiesRouteImport.update({
  id: '/energy/utilities',
  path: '/energy/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyWasteRoute = EnergyWasteRouteImport.update({
  id: '/energy/waste',
  path: '/energy/waste',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryFinishedRoute = InventoryFinishedRouteImport.update({
  id: '/inventory/finished',
  path: '/inventory/finished',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProcurementRoute = InventoryProcurementRouteImport.update({
  id: '/inventory/procurement',
  path: '/inventory/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRawRoute = InventoryRawRouteImport.update({
  id: '/inventory/raw',
  path: '/inventory/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryVendorsRoute = InventoryVendorsRouteImport.update({
  id: '/inventory/vendors',
  path: '/inventory/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveAlertsRoute = PredictiveAlertsRouteImport.update({
  id: '/predictive/alerts',
  path: '/predictive/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveHealthRoute = PredictiveHealthRouteImport.update({
  id: '/predictive/health',
  path: '/predictive/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveSimulationRoute = PredictiveSimulationRouteImport.update({
  id: '/predictive/simulation',
  path: '/predictive/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveWorkOrdersRoute = PredictiveWorkOrdersRouteImport.update({
  id: '/predictive/work-orders',
  path: '/predictive/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityCapaRoute = QualityCapaRouteImport.update({
  id: '/quality/capa',
  path: '/quality/capa',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityCoaRoute = QualityCoaRouteImport.update({
  id: '/quality/coa',
  path: '/quality/coa',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityIpcRoute = QualityIpcRouteImport.update({
  id: '/quality/ipc',
  path: '/quality/ipc',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityReleaseRoute = QualityReleaseRouteImport.update({
  id: '/quality/release',
  path: '/quality/release',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPlantRoute = SettingsPlantRouteImport.update({
  id: '/settings/plant',
  path: '/settings/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSensorsRoute = SettingsSensorsRouteImport.update({
  id: '/settings/sensors',
  path: '/settings/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/floor': typeof FloorRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/shifts': typeof ShiftsRoute
  '/analytics/downtime': typeof AnalyticsDowntimeRoute
  '/analytics/oee': typeof AnalyticsOeeRoute
  '/analytics/reports': typeof AnalyticsReportsRoute
  '/analytics/schedule': typeof AnalyticsScheduleRoute
  '/compliance/audit': typeof ComplianceAuditRoute
  '/compliance/ebmr': typeof ComplianceEbmrRoute
  '/compliance/sop': typeof ComplianceSopRoute
  '/ehs/emissions': typeof EhsEmissionsRoute
  '/ehs/hazards': typeof EhsHazardsRoute
  '/ehs/incidents': typeof EhsIncidentsRoute
  '/ehs/ppe': typeof EhsPpeRoute
  '/energy/carbon': typeof EnergyCarbonRoute
  '/energy/utilities': typeof EnergyUtilitiesRoute
  '/energy/waste': typeof EnergyWasteRoute
  '/inventory/finished': typeof InventoryFinishedRoute
  '/inventory/procurement': typeof InventoryProcurementRoute
  '/inventory/raw': typeof InventoryRawRoute
  '/inventory/vendors': typeof InventoryVendorsRoute
  '/predictive/alerts': typeof PredictiveAlertsRoute
  '/predictive/health': typeof PredictiveHealthRoute
  '/predictive/simulation': typeof PredictiveSimulationRoute
  '/predictive/work-orders': typeof PredictiveWorkOrdersRoute
  '/quality/capa': typeof QualityCapaRoute
  '/quality/coa': typeof QualityCoaRoute
  '/quality/ipc': typeof QualityIpcRoute
  '/quality/release': typeof QualityReleaseRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/plant': typeof SettingsPlantRoute
  '/settings/sensors': typeof SettingsSensorsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/energy/': typeof EnergyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/floor': typeof FloorRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/shifts': typeof ShiftsRoute
  '/analytics/downtime': typeof AnalyticsDowntimeRoute
  '/analytics/oee': typeof AnalyticsOeeRoute
  '/analytics/reports': typeof AnalyticsReportsRoute
  '/analytics/schedule': typeof AnalyticsScheduleRoute
  '/compliance/audit': typeof ComplianceAuditRoute
  '/compliance/ebmr': typeof ComplianceEbmrRoute
  '/compliance/sop': typeof ComplianceSopRoute
  '/ehs/emissions': typeof EhsEmissionsRoute
  '/ehs/hazards': typeof EhsHazardsRoute
  '/ehs/incidents': typeof EhsIncidentsRoute
  '/ehs/ppe': typeof EhsPpeRoute
  '/energy/carbon': typeof EnergyCarbonRoute
  '/energy/utilities': typeof EnergyUtilitiesRoute
  '/energy/waste': typeof EnergyWasteRoute
  '/inventory/finished': typeof InventoryFinishedRoute
  '/inventory/procurement': typeof InventoryProcurementRoute
  '/inventory/raw': typeof InventoryRawRoute
  '/inventory/vendors': typeof InventoryVendorsRoute
  '/predictive/alerts': typeof PredictiveAlertsRoute
  '/predictive/health': typeof PredictiveHealthRoute
  '/predictive/simulation': typeof PredictiveSimulationRoute
  '/predictive/work-orders': typeof PredictiveWorkOrdersRoute
  '/quality/capa': typeof QualityCapaRoute
  '/quality/coa': typeof QualityCoaRoute
  '/quality/ipc': typeof QualityIpcRoute
  '/quality/release': typeof QualityReleaseRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/plant': typeof SettingsPlantRoute
  '/settings/sensors': typeof SettingsSensorsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/compliance': typeof ComplianceIndexRoute
  '/energy': typeof EnergyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/floor': typeof FloorRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/shifts': typeof ShiftsRoute
  '/analytics/downtime': typeof AnalyticsDowntimeRoute
  '/analytics/oee': typeof AnalyticsOeeRoute
  '/analytics/reports': typeof AnalyticsReportsRoute
  '/analytics/schedule': typeof AnalyticsScheduleRoute
  '/compliance/audit': typeof ComplianceAuditRoute
  '/compliance/ebmr': typeof ComplianceEbmrRoute
  '/compliance/sop': typeof ComplianceSopRoute
  '/ehs/emissions': typeof EhsEmissionsRoute
  '/ehs/hazards': typeof EhsHazardsRoute
  '/ehs/incidents': typeof EhsIncidentsRoute
  '/ehs/ppe': typeof EhsPpeRoute
  '/energy/carbon': typeof EnergyCarbonRoute
  '/energy/utilities': typeof EnergyUtilitiesRoute
  '/energy/waste': typeof EnergyWasteRoute
  '/inventory/finished': typeof InventoryFinishedRoute
  '/inventory/procurement': typeof InventoryProcurementRoute
  '/inventory/raw': typeof InventoryRawRoute
  '/inventory/vendors': typeof InventoryVendorsRoute
  '/predictive/alerts': typeof PredictiveAlertsRoute
  '/predictive/health': typeof PredictiveHealthRoute
  '/predictive/simulation': typeof PredictiveSimulationRoute
  '/predictive/work-orders': typeof PredictiveWorkOrdersRoute
  '/quality/capa': typeof QualityCapaRoute
  '/quality/coa': typeof QualityCoaRoute
  '/quality/ipc': typeof QualityIpcRoute
  '/quality/release': typeof QualityReleaseRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/plant': typeof SettingsPlantRoute
  '/settings/sensors': typeof SettingsSensorsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/energy/': typeof EnergyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/floor'
    | '/health'
    | '/login'
    | '/production'
    | '/shifts'
    | '/analytics/downtime'
    | '/analytics/oee'
    | '/analytics/reports'
    | '/analytics/schedule'
    | '/compliance/audit'
    | '/compliance/ebmr'
    | '/compliance/sop'
    | '/ehs/emissions'
    | '/ehs/hazards'
    | '/ehs/incidents'
    | '/ehs/ppe'
    | '/energy/carbon'
    | '/energy/utilities'
    | '/energy/waste'
    | '/inventory/finished'
    | '/inventory/procurement'
    | '/inventory/raw'
    | '/inventory/vendors'
    | '/predictive/alerts'
    | '/predictive/health'
    | '/predictive/simulation'
    | '/predictive/work-orders'
    | '/quality/capa'
    | '/quality/coa'
    | '/quality/ipc'
    | '/quality/release'
    | '/settings/integrations'
    | '/settings/plant'
    | '/settings/sensors'
    | '/settings/users'
    | '/compliance/'
    | '/energy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/floor'
    | '/health'
    | '/login'
    | '/production'
    | '/shifts'
    | '/analytics/downtime'
    | '/analytics/oee'
    | '/analytics/reports'
    | '/analytics/schedule'
    | '/compliance/audit'
    | '/compliance/ebmr'
    | '/compliance/sop'
    | '/ehs/emissions'
    | '/ehs/hazards'
    | '/ehs/incidents'
    | '/ehs/ppe'
    | '/energy/carbon'
    | '/energy/utilities'
    | '/energy/waste'
    | '/inventory/finished'
    | '/inventory/procurement'
    | '/inventory/raw'
    | '/inventory/vendors'
    | '/predictive/alerts'
    | '/predictive/health'
    | '/predictive/simulation'
    | '/predictive/work-orders'
    | '/quality/capa'
    | '/quality/coa'
    | '/quality/ipc'
    | '/quality/release'
    | '/settings/integrations'
    | '/settings/plant'
    | '/settings/sensors'
    | '/settings/users'
    | '/compliance'
    | '/energy'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/floor'
    | '/health'
    | '/login'
    | '/production'
    | '/shifts'
    | '/analytics/downtime'
    | '/analytics/oee'
    | '/analytics/reports'
    | '/analytics/schedule'
    | '/compliance/audit'
    | '/compliance/ebmr'
    | '/compliance/sop'
    | '/ehs/emissions'
    | '/ehs/hazards'
    | '/ehs/incidents'
    | '/ehs/ppe'
    | '/energy/carbon'
    | '/energy/utilities'
    | '/energy/waste'
    | '/inventory/finished'
    | '/inventory/procurement'
    | '/inventory/raw'
    | '/inventory/vendors'
    | '/predictive/alerts'
    | '/predictive/health'
    | '/predictive/simulation'
    | '/predictive/work-orders'
    | '/quality/capa'
    | '/quality/coa'
    | '/quality/ipc'
    | '/quality/release'
    | '/settings/integrations'
    | '/settings/plant'
    | '/settings/sensors'
    | '/settings/users'
    | '/compliance/'
    | '/energy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  FloorRoute: typeof FloorRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRoute
  ShiftsRoute: typeof ShiftsRoute
  AnalyticsDowntimeRoute: typeof AnalyticsDowntimeRoute
  AnalyticsOeeRoute: typeof AnalyticsOeeRoute
  AnalyticsReportsRoute: typeof AnalyticsReportsRoute
  AnalyticsScheduleRoute: typeof AnalyticsScheduleRoute
  ComplianceAuditRoute: typeof ComplianceAuditRoute
  ComplianceEbmrRoute: typeof ComplianceEbmrRoute
  ComplianceSopRoute: typeof ComplianceSopRoute
  EhsEmissionsRoute: typeof EhsEmissionsRoute
  EhsHazardsRoute: typeof EhsHazardsRoute
  EhsIncidentsRoute: typeof EhsIncidentsRoute
  EhsPpeRoute: typeof EhsPpeRoute
  EnergyCarbonRoute: typeof EnergyCarbonRoute
  EnergyUtilitiesRoute: typeof EnergyUtilitiesRoute
  EnergyWasteRoute: typeof EnergyWasteRoute
  InventoryFinishedRoute: typeof InventoryFinishedRoute
  InventoryProcurementRoute: typeof InventoryProcurementRoute
  InventoryRawRoute: typeof InventoryRawRoute
  InventoryVendorsRoute: typeof InventoryVendorsRoute
  PredictiveAlertsRoute: typeof PredictiveAlertsRoute
  PredictiveHealthRoute: typeof PredictiveHealthRoute
  PredictiveSimulationRoute: typeof PredictiveSimulationRoute
  PredictiveWorkOrdersRoute: typeof PredictiveWorkOrdersRoute
  QualityCapaRoute: typeof QualityCapaRoute
  QualityCoaRoute: typeof QualityCoaRoute
  QualityIpcRoute: typeof QualityIpcRoute
  QualityReleaseRoute: typeof QualityReleaseRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsPlantRoute: typeof SettingsPlantRoute
  SettingsSensorsRoute: typeof SettingsSensorsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
  EnergyIndexRoute: typeof EnergyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/downtime': {
      id: '/analytics/downtime'
      path: '/analytics/downtime'
      fullPath: '/analytics/downtime'
      preLoaderRoute: typeof AnalyticsDowntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/oee': {
      id: '/analytics/oee'
      path: '/analytics/oee'
      fullPath: '/analytics/oee'
      preLoaderRoute: typeof AnalyticsOeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/reports': {
      id: '/analytics/reports'
      path: '/analytics/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AnalyticsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/schedule': {
      id: '/analytics/schedule'
      path: '/analytics/schedule'
      fullPath: '/analytics/schedule'
      preLoaderRoute: typeof AnalyticsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/audit': {
      id: '/compliance/audit'
      path: '/compliance/audit'
      fullPath: '/compliance/audit'
      preLoaderRoute: typeof ComplianceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/ebmr': {
      id: '/compliance/ebmr'
      path: '/compliance/ebmr'
      fullPath: '/compliance/ebmr'
      preLoaderRoute: typeof ComplianceEbmrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/sop': {
      id: '/compliance/sop'
      path: '/compliance/sop'
      fullPath: '/compliance/sop'
      preLoaderRoute: typeof ComplianceSopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ehs/emissions': {
      id: '/ehs/emissions'
      path: '/ehs/emissions'
      fullPath: '/ehs/emissions'
      preLoaderRoute: typeof EhsEmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ehs/hazards': {
      id: '/ehs/hazards'
      path: '/ehs/hazards'
      fullPath: '/ehs/hazards'
      preLoaderRoute: typeof EhsHazardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ehs/incidents': {
      id: '/ehs/incidents'
      path: '/ehs/incidents'
      fullPath: '/ehs/incidents'
      preLoaderRoute: typeof EhsIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ehs/ppe': {
      id: '/ehs/ppe'
      path: '/ehs/ppe'
      fullPath: '/ehs/ppe'
      preLoaderRoute: typeof EhsPpeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/': {
      id: '/energy/'
      path: '/energy'
      fullPath: '/energy/'
      preLoaderRoute: typeof EnergyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/carbon': {
      id: '/energy/carbon'
      path: '/energy/carbon'
      fullPath: '/energy/carbon'
      preLoaderRoute: typeof EnergyCarbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/utilities': {
      id: '/energy/utilities'
      path: '/energy/utilities'
      fullPath: '/energy/utilities'
      preLoaderRoute: typeof EnergyUtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/waste': {
      id: '/energy/waste'
      path: '/energy/waste'
      fullPath: '/energy/waste'
      preLoaderRoute: typeof EnergyWasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/finished': {
      id: '/inventory/finished'
      path: '/inventory/finished'
      fullPath: '/inventory/finished'
      preLoaderRoute: typeof InventoryFinishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/procurement': {
      id: '/inventory/procurement'
      path: '/inventory/procurement'
      fullPath: '/inventory/procurement'
      preLoaderRoute: typeof InventoryProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/raw': {
      id: '/inventory/raw'
      path: '/inventory/raw'
      fullPath: '/inventory/raw'
      preLoaderRoute: typeof InventoryRawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/vendors': {
      id: '/inventory/vendors'
      path: '/inventory/vendors'
      fullPath: '/inventory/vendors'
      preLoaderRoute: typeof InventoryVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive/alerts': {
      id: '/predictive/alerts'
      path: '/predictive/alerts'
      fullPath: '/predictive/alerts'
      preLoaderRoute: typeof PredictiveAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive/health': {
      id: '/predictive/health'
      path: '/predictive/health'
      fullPath: '/predictive/health'
      preLoaderRoute: typeof PredictiveHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive/simulation': {
      id: '/predictive/simulation'
      path: '/predictive/simulation'
      fullPath: '/predictive/simulation'
      preLoaderRoute: typeof PredictiveSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive/work-orders': {
      id: '/predictive/work-orders'
      path: '/predictive/work-orders'
      fullPath: '/predictive/work-orders'
      preLoaderRoute: typeof PredictiveWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/capa': {
      id: '/quality/capa'
      path: '/quality/capa'
      fullPath: '/quality/capa'
      preLoaderRoute: typeof QualityCapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/coa': {
      id: '/quality/coa'
      path: '/quality/coa'
      fullPath: '/quality/coa'
      preLoaderRoute: typeof QualityCoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/ipc': {
      id: '/quality/ipc'
      path: '/quality/ipc'
      fullPath: '/quality/ipc'
      preLoaderRoute: typeof QualityIpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/release': {
      id: '/quality/release'
      path: '/quality/release'
      fullPath: '/quality/release'
      preLoaderRoute: typeof QualityReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/plant': {
      id: '/settings/plant'
      path: '/settings/plant'
      fullPath: '/settings/plant'
      preLoaderRoute: typeof SettingsPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sensors': {
      id: '/settings/sensors'
      path: '/settings/sensors'
      fullPath: '/settings/sensors'
      preLoaderRoute: typeof SettingsSensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  FloorRoute: FloorRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRoute,
  ShiftsRoute: ShiftsRoute,
  AnalyticsDowntimeRoute: AnalyticsDowntimeRoute,
  AnalyticsOeeRoute: AnalyticsOeeRoute,
  AnalyticsReportsRoute: AnalyticsReportsRoute,
  AnalyticsScheduleRoute: AnalyticsScheduleRoute,
  ComplianceAuditRoute: ComplianceAuditRoute,
  ComplianceEbmrRoute: ComplianceEbmrRoute,
  ComplianceSopRoute: ComplianceSopRoute,
  EhsEmissionsRoute: EhsEmissionsRoute,
  EhsHazardsRoute: EhsHazardsRoute,
  EhsIncidentsRoute: EhsIncidentsRoute,
  EhsPpeRoute: EhsPpeRoute,
  EnergyCarbonRoute: EnergyCarbonRoute,
  EnergyUtilitiesRoute: EnergyUtilitiesRoute,
  EnergyWasteRoute: EnergyWasteRoute,
  InventoryFinishedRoute: InventoryFinishedRoute,
  InventoryProcurementRoute: InventoryProcurementRoute,
  InventoryRawRoute: InventoryRawRoute,
  InventoryVendorsRoute: InventoryVendorsRoute,
  PredictiveAlertsRoute: PredictiveAlertsRoute,
  PredictiveHealthRoute: PredictiveHealthRoute,
  PredictiveSimulationRoute: PredictiveSimulationRoute,
  PredictiveWorkOrdersRoute: PredictiveWorkOrdersRoute,
  QualityCapaRoute: QualityCapaRoute,
  QualityCoaRoute: QualityCoaRoute,
  QualityIpcRoute: QualityIpcRoute,
  QualityReleaseRoute: QualityReleaseRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsPlantRoute: SettingsPlantRoute,
  SettingsSensorsRoute: SettingsSensorsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
  EnergyIndexRoute: EnergyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
